---
name: Awesome List Workflow
"on":
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:
    name: Lint awesome list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run awesome-lint
        run: npx awesome-lint
